[package]
name = "pychainql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pychainql"
crate-type = ["cdylib"]

[dependencies]
chainql-core = "0.4.7"
pyo3 = "0.22.0"
