[package]
name = "chainql"
version = "0.1.0"
edition = "2021"

[lib]
name = "chainql"
crate-type = ["cdylib"]

[dependencies]
chainql-core = { path = "../chainql/crates/chainql-core" }
jrsonnet-evaluator = { version = "0.5.0-pre95" }
pyo3 = { version = "0.23.1", features = ["extension-module", "num-bigint"] }
ss58-registry = "1.34.0"
stacker = "0.1.17"
tokio = { version = "1.41.1", default-features = false, features = ["rt", "rt-multi-thread"] }
