[package]
name = "chainql"
version = "0.1.0"
edition = "2021"

[lib]
name = "chainql"
crate-type = ["cdylib"]

[dependencies]
chainql-core = { path = "../chainql/crates/chainql-core" }
pyo3 = { version = "0.23.1", features = ["extension-module"] }
ss58-registry = "1.51.0"
