[package]
name = "chainql"
version = "0.4.7-beta"
edition = "2021"

[lib]
name = "chainql"
crate-type = ["cdylib"]

[dependencies]
chainql-core = { git = "https://github.com/UniqueNetwork/chainql.git", branch = "pub-builtin" }
either = "1.13.0"
gag = "1.0.0"
jrsonnet-evaluator = { version = "0.5.0-pre95" }
num-bigint = "0.4.6"
ss58-registry = "1.34.0"
tokio = { version = "1.41.1", default-features = false, features = ["rt", "rt-multi-thread"] }

[dependencies.pyo3]
version = "0.23.1"
features = ["abi3-py310", "extension-module", "num-bigint", "either"]

[profile.release]
opt-level = 3
lto = "thin"
strip = "debuginfo"
panic = "unwind"
