[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "chainql"
requires-python = ">=3.10"
classifiers = []
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]