[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "chainql"
requires-python = ">=3.10"
classifiers = []
dynamic = ["version"]
dependencies = [
    "pdoc==15.0.0"
]

[tool.maturin]
python-source = "python"
features = ["pyo3/extension-module"]